version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ../src:/app/src
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENVIRONMENT=development
      - SECRET_KEY=your_secret_key_here
      - DATABASE=postgres
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password

volumes:
  postgres_data:

